//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HFzhCNResourceDLL.rc
//
#define IDR_DRAWWINDOW                  101
#define IDR_MAINWINDOW                  102
#define IDS_DRAWWINDOW_MBDOWN           103
#define IDS_DRAWWINDOW_INFOBAR_PANE1    104
#define IDS_DRAWWINDOW_INFOBAR_PANE2    105
#define IDS_DRAWWINDOW_INFOBAR_PANE3    106
#define IDS_DRAWWINDOW_INFOBAR_PANE4    107
#define IDS_DRAWWINDOW_INFOBAR_NOTINIMAGE 108
#define IDS_DRAWWINDOW_TITLE            109
#define IDS_MAINWINDOW_TITLE            110
#define IDS_MAINWINDOW_STEP1_TITLE      111
#define IDS_MAINWINDOW_STEP1_LBLPAK     112
#define IDS_MAINWINDOW_STEP1_BROWSE     113
#define IDS_MAINWINDOW_STEP2_TITLE      114
#define IDS_MAINWINDOW_STEP2_LBLHEADERSELECT 115
#define IDS_MAINWINDOW_STEP2_LBLFONTSELECT 116
#define IDS_MAINWINDOW_STEP2_LBLSIZE    117
#define IDS_MAINWINDOW_STEP2_LBLBOLD    118
#define IDS_MAINWINDOW_STEP2_BTNITALIC  119
#define IDS_MAINWINDOW_STEP2_BTNUNDERLINE 120
#define IDS_MAINWINDOW_STEP2_SAMPLETEXT 121
#define IDS_MAINWINDOW_STEP3_TITLE      122
#define IDS_MAINWINDOW_STEP3_BTNRUN     123
#define IDS_MAINWINDOW_STEP3_PREVIEW    124
#define IDS_MAINWINDOW_STEP4_TITLE      125
#define IDS_MAINWINDOW_STEP4_BTNPACKAGE 126
#define IDS_MAINWINDOW_STEP4_BTNOPENFOLDER 127
#define IDS_MAINWINDOW_STEP1_PAKFILTER  128
#define IDS_MAINWINDOW_STEP1_INVALIDPAK 129
#define IDS_MAINWINDOW_STEP2_INVALIDBOLD 130
#define IDS_MAINWINDOW_STEP2_LBLPADDING 131
#define IDS_MAINWINDOW_STEP2_LBLVPOSITION 132
#define IDS_LOG_APPSTART                400
#define IDS_LOG_NUM_FONTS_LOADED        401
#define IDS_LOG_NUM_UNICODES_IN_FONT    402
#define IDS_LOG_FONT_FILE_NOT_SUPPORTED 403
#define IDS_LOG_NUM_UNICODES_READ       404
#define IDS_LOG_NUM_ABC_READ            405
#define IDS_LOG_DIMENSION_REQUIRED      406
#define IDS_LOG_NOW_EXECUTING           407
#define IDS_LOG_WRONG_EXIT_CODE         408
#define IDS_LOG_FILE_NOT_FOUND          409
#define IDS_LOG_NOT_PROPER_XML          410
#define IDS_LOG_XML_UID_NOT_FOUND       411
#define IDM_WINDOWS_LOG                 40015
#define IDM_HELP_README                 40017
#define IDM_HELP_ONLINE                 40018
#define IDM_HELP_ABOUT                  40019
#define IDM_LANGUAGE_ENGLISH            40020
#define IDM_LANGUAGE_CHINESE            40021
#define IDM_DRAWWINDOW_PREV             40024
#define IDM_DRAWWINDOW_NEXT             40025
#define IDM_DRAWWINDOW_ZOOMIN           40027
#define IDM_DRAWWINDOW_ZOOMOUT          40029
#define IDM_DRAWWINDOW_100              40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
